name: build_website

on:
  push:
    branches: [ autodata ]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: master
     
      - name: Download data
        run: |
          curl -LO https://github.com/woefe/covid19stats/archive/autodata.zip
          unzip -d /tmp autodata.zip
          rm autodata.zip

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Convert notebook to HTML
        run: |
          jupyter nbconvert \
            --to html 
            --no-input 
            --template lab_condensed 
            --TemplateExporter.extra_template_basedirs="nbconvert_template" 
            --execute
            --output index.html
            condensed.ipynb

      - name: Upload index.html artifact
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: index.html
      
