name: "Get Data"

on:
  schedule:
    - cron: '25 9 * * *'

jobs:
  getdata:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_AUTHOR_NAME: "GitHub Action"
      GIT_COMMITTER_NAME: "GitHub Action"
      GIT_AUTHOR_EMAIL: "octobot@github.kom"
      GIT_COMMITTER_EMAIL: "cotobot@github.kom"
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Downloading data
      run: |
        git switch -c data
        mkdir -p data
        curl -Lo "data/$(date --iso-8601=date)" https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data

    - name: Commiting data
      run: |
        git add data
        git commit --no-edit -m "Update data"
        git push "https://woefe:$GITHUB_TOKEN@github.com/woefe/covid19stats.git" data
