name: "Get Data"

on:
  schedule:
    - cron: '25 9 * * *'

jobs:
  getdata:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: autodata

    - name: Downloading data
      run: curl -Lo "data/silo/$(date --iso-8601=date).csv" https://www.arcgis.com/sharing/rest/content/items/f10774f1c63e40168479a1feb6c7ca74/data

    - name: Commiting data
      run: |
        git config user.email "octobot@github.kom"
        git config user.name "GitHub Action"
        git add "data/silo"
        git commit --no-edit -m "Update data"
        git push "https://woefe:$GITHUB_TOKEN@github.com/woefe/covid19stats.git" autodata
